CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE CLIENTE (CLI_CPF INT PRIMARY KEY NOT NULL, CLI_NOME VARCHAR(50), CLI_ENDERECO VARCHAR(50), CLI_EMAIL VARCHAR(20), CLI_FONE VARCHAR(20));

CREATE TABLE VENDENDOR (VEN_COD INT IDENTITY(1000,1) PRIMARY KEY NOT NULL, VEN_NOME VARCHAR(50), VEN_FONE VARCHAR(20));

CREATE TABLE FORMA_PAGTO (FORM_COD INT PRIMARY KEY NOT NULL, FORM_DES VARCHAR(10));

CREATE TABLE VENDA (VEND_NPED INT IDENTITY(1000,1) PRIMARY KEY NOT NULL, CLI_CPF INT, VEN_COD INT, DATA DATE, TOTAL_VENDA DECIMAL(10,2),
FOREIGN KEY (CLI_CPF) REFERENCES CLIENTE,
FOREIGN KEY (VEN_COD) REFERENCES VENDENDOR);

CREATE TABLE FORNECEDOR (FORN_COD INT IDENTITY(100,1) PRIMARY KEY NOT NULL, FORN_NOME VARCHAR(50), FORN_FONE VARCHAR(50));

CREATE TABLE CATEGORIA (CAT_COD INT IDENTITY(1000,1) PRIMARY KEY NOT NULL, CAT_DESC VARCHAR (50));

CREATE TABLE AUTOR (AUTOR_COD INT IDENTITY(1000,1) PRIMARY KEY NOT NULL, AUTOR_NOME VARCHAR(50));

CREATE TABLE PRODUTO (PROD_COD INT IDENTITY(1000,1) PRIMARY KEY NOT NULL, PROD_TITULO VARCHAR(50), PROD_PRECO DECIMAL(10,2), AUTOR_COD INT, FORN_COD INT, CAT_COD INT
FOREIGN KEY (AUTOR_COD) REFERENCES AUTOR,
FOREIGN KEY (FORN_COD) REFERENCES FORNECEDOR,
FOREIGN KEY (CAT_COD) REFERENCES CATEGORIA);

CREATE TABLE VENDA_PRODUTO (VEND_NPED INT, PROD_COD INT, QTD INT, PRECO DECIMAL(10,2), TOTAL DECIMAL (10,2)
FOREIGN KEY (VEND_NPED) REFERENCES VENDA,
FOREIGN KEY (PROD_COD) REFERENCES PRODUTO);
                                
								
								 